sudo: true

before_install:
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq lyx
  - sudo apt-get install -qq texlive
  #- sudo apt-get install -qq texlive*
  #- sudo apt-get install -qq texlive-latex-extra
  #- sudo apt-get install -qq texlive-fonts-extra
  - sudo apt-get install -qq pgf
  - sudo apt-get install -qq graphviz
  - sudo apt-get install -qq qtikz
  #- sudo apt-get install -qq tlmgr
  #- sudo tlmgr pgf ms

script:


after_script:


after_success:
  - echo "success"
 
after_failure:
  - echo "failure"
